experiment_data_recorder:
  output_dir: "~/rosbag/uav_contact"
  file_prefix: "uav_contact_exp"
  record_topics:
    - "/uav_contact/trajectory/reference"
    - "/mavros/local_position/pose"
    - "/mavros/local_position/velocity_local"
    - "/uav_contact/diagnostics/position_error_ref_minus_meas"
    - "/uav_contact/diagnostics/velocity_error_ref_minus_meas"
    - "/mavros/state"
    - "/uav_contact/task/phase"
    - "/uav_contact/safety/state"
    - "/uav_contact/contact/normal_velocity_cmd"
    - "/mavros/setpoint_raw/local"
    - "/uav_contact/task/sliding_done"
    - "/servo/command"
    - "/contact/distance"
    - "/joint_states"
    - "/mavros/setpoint_raw/target_local"
    - "/mavros/local_position/odom"
    - "/mavros/imu/data"
    - "/end_effector_velocity"
