joint_servo_bridge:
  publish_rate_hz: 50.0
  joint_min: -1.57
  joint_max: 1.57
  neutral_theta: 0.0
  enable_in_phases:
    - 2  # APPROACH
    - 3  # INITIAL_CONTACT
    - 4  # SLIDING_CONTACT
    - 5  # RETREAT
  output_mode: "topic"  # dynamixel | topic
  servo_joint_offset: -0.52
  servo_operating_mode: 4
  servo_profile_velocity: 30
  dxl_id: 1
  dxl_baudrate: 57600
  dxl_devicename: "/dev/ttyUSB1"

joint_servo_gazebo_relay:
  enabled: true
  input_topic: "/servo/command"
  output_topic: "/skyvortex/operator_1_joint/pos_cmd"
  joint_offset: -0.52
